name: bump_version
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ CI ]
    types: [ completed ]
    branches: [ master ]

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: {% raw %}"${{ secrets.GITHUB_TOKEN }}"{% endraw %}

      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: {% raw %}"${{ secrets.GITHUB_TOKEN }}"{% endraw %}
          changelog_increment_filename: body.md

      - name: Setup go-task
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.29.1

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "{{ cookiecutter.minimal_python_version }}"

      - name: setup poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: |
          task init
          task build

      - name: Configure TestPyPI
        run: | 
            poetry config repositories.test-pypi https://test.pypi.org/legacy/
            poetry config pypi-token.test-pypi {% raw %}${{ secrets.TEST_PYPI_API_TOKEN }}{% endraw %}

      - name: Publish package to Test Pypi
        run: poetry publish -r test-pypi

      - name: Install package from TestPyPI
        run: pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple {{ cookiecutter.minimal_python_version }}

      - name: Configure PyPI
        run: poetry config pypi-token.pypi {% raw %}${{ secrets.PYPI_API_TOKEN }}{% endraw %}

      - name: Publish package to PyPI
        run: poetry publish

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          body_path: "body.md"
          tag_name: {% raw %}${{ env.REVISION }}{% endraw %}
        env:
          GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}