name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version:
        {% for version in cookiecutter._compatible_versions_range[cookiecutter._compatible_versions_range.index(cookiecutter.minimal_python_version):] %}
          - "{{ version }}"
        {% endfor %}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go-task
        uses: pnorton5432/setup-task@v1
        with:
          task-version: 3.29.1

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: setup poetry
        uses: abatilo/actions-poetry@v2

      - name: Install dependencies
        run: task init

      - name: run test
        run: task test
